# Generated by Django 4.2.7 on 2025-03-15 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('capacity', models.IntegerField()),
                ('available_slots', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='donation',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='donations',
            field=models.ManyToManyField(related_name='items', to='donors.donation'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='status',
            field=models.CharField(choices=[('fresh', 'Fresh'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired')], default='fresh', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(limit_choices_to={'role': 'donor'}, on_delete=django.db.models.deletion.CASCADE, to='donors.user'),
        ),
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to='donors.user')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='collection_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donors.collectionpoint'),
        ),
    ]
