# Generated by Django 4.2.7 on 2025-03-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_remove_fooditem_donations_collectionpoint_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpoint',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
